### ISSUE TITLE
Exception on http2 when route is not available

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/nukleus-http2.java#18]
```
docker  | java.util.NoSuchElementException: No value present
docker  | 	at java.util.Optional.get(Optional.java:135)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.doHeaders(SourceInputStreamFactory.java:882)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.decodeHttp2Frame(SourceInputStreamFactory.java:751)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.processData(SourceInputStreamFactory.java:413)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.streamAfterBeginOrData(SourceInputStreamFactory.java:285)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.handleStream(SourceInputStreamFactory.java:257)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.access$3400(SourceInputStreamFactory.java:178)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory.lambda$newStream$39(SourceInputStreamFactory.java:175)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.Source.handleRead(Source.java:141)
docker  | 	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:198)
docker  | 	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:157)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.Source.process(Source.java:100)
docker  | 	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
docker  | 	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
docker  | 	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
docker  | 	at org.reaktivity.reaktor.Reaktor.lambda$supplyWorker$0(Reaktor.java:154)
docker  | 	at org.reaktivity.reaktor.Reaktor$1.doWork(Reaktor.java:132)
docker  | 	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
docker  | 	at java.lang.Thread.run(Thread.java:745)
docker  | java.lang.NullPointerException
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.doData(SourceInputStreamFactory.java:1018)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.decodeHttp2Frame(SourceInputStreamFactory.java:747)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.processData(SourceInputStreamFactory.java:413)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.streamAfterBeginOrData(SourceInputStreamFactory.java:285)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.handleStream(SourceInputStreamFactory.java:257)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory$SourceInputStream.access$3400(SourceInputStreamFactory.java:178)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.stream.SourceInputStreamFactory.lambda$newStream$39(SourceInputStreamFactory.java:175)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.Source.handleRead(Source.java:141)
docker  | 	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:198)
docker  | 	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:157)
docker  | 	at org.reaktivity.nukleus.http2.internal.routable.Source.process(Source.java:100)
docker  | 	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
docker  | 	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
docker  | 	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
docker  | 	at org.reaktivity.reaktor.Reaktor.lambda$supplyWorker$0(Reaktor.java:154)
docker  | 	at org.reaktivity.reaktor.Reaktor$1.doWork(Reaktor.java:132)
docker  | 	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
docker  | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jfallows** [comment]
Duplicates #41 after moving to shared `reaktor` core.
