### ISSUE TITLE
Request for an authority that is not routed by the http2 nuklei results in NPE

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/nukleus-http2.java#41]
Should be 404

```
           | java.lang.NullPointerException
           | 	at org.reaktivity.nukleus.http2.internal.Http2Connection.doHeaders(Http2Connection.java:672)
           | 	at org.reaktivity.nukleus.http2.internal.Http2Connection.decodeHttp2Frame(Http2Connection.java:542)
           | 	at org.reaktivity.nukleus.http2.internal.Http2Connection.handleData(Http2Connection.java:204)
           | 	at org.reaktivity.nukleus.http2.internal.ServerStreamFactory$ServerAcceptStream.handleData(ServerStreamFactory.java:332)
           | 	at org.reaktivity.nukleus.http2.internal.ServerStreamFactory$ServerAcceptStream.afterBegin(ServerStreamFactory.java:276)
           | 	at org.reaktivity.nukleus.http2.internal.ServerStreamFactory$ServerAcceptStream.handleStream(ServerStreamFactory.java:246)
           | 	at org.reaktivity.nukleus.http2.internal.ServerStreamFactory$ServerAcceptStream.access$1200(ServerStreamFactory.java:217)
           | 	at org.reaktivity.nukleus.http2.internal.ServerStreamFactory.lambda$newAcceptStream$1(ServerStreamFactory.java:193)
           | 	at org.reaktivity.reaktor.internal.acceptable.Source.handleRead(Source.java:162)
           | 	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:198)
           | 	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:157)
           | 	at org.reaktivity.reaktor.internal.acceptable.Source.process(Source.java:85)
           | 	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
           | 	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
           | 	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
           | 	at org.reaktivity.reaktor.Reaktor.lambda$supplyWorker$0(Reaktor.java:170)
           | 	at org.reaktivity.reaktor.Reaktor$1.doWork(Reaktor.java:112)
           | 	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
           | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jfallows** [comment]
This needs an update to the spec scripts to verify `404` status code response for missing routes.
